### ISSUE TITLE
How to compile this program into exe ???

### ISSUE THREAD

**Issue by GetRektBoy724** [RythmStick/AMSITrigger#3]

**Comment by RythmStick** [comment]
Hi GetRektBoy724 - I use Visual studio.

**Comment by GetRektBoy724** [comment]
@RythmStick cause i NEVER use visual studio...where should i click?

**Comment by RythmStick** [comment]
Just use Build/Build solution or hit F6

**Comment by GetRektBoy724** [comment]
hey @RythmStick can you just compile the exe for me......pls

**Comment by GetRektBoy724** [comment]
i also run the visual studio at linux

**Comment by Maleick** [comment]
lololol

> hey @RythmStick can you just compile the exe for me......pls

**Comment by RythmStick** [comment]
Sure. Give me half an hour....

**Comment by RythmStick** [comment]
Ok - Latest releases [here](https://github.com/RythmStick/AMSITrigger/releases/tag/v3)

**Comment by RythmStick** [comment]
V3 releases available in GitHub now

**Comment by GetRektBoy724** [comment]
thx :)
