### ISSUE TITLE
"Check Real Time protection is enabled" error

### ISSUE THREAD

**Issue by eXPeri3nc3** [RythmStick/AMSITrigger#4]
Hi, I tried the release binary, and downloading the sourcecode to compile and run it

I tested with a Powershell script, but I can only see the "[+] Check Real Time protection is enabled" error, while my Windows Defender protection is all turned on.
I tried --inputfile and -u, but still same error, for the v2 release binary, and v3 selfcompile

Is there a way for me to diagnose further what could be the issue? Thanks!

**Comment by RythmStick** [comment]
Hi eXPeri3nc3 - the protectionenabled method check runs initially and passes the text "amsiscanbuffer" (a known trigger)  to AMSIScanBuffer. 

As a test, you could run powershell and see whether that string produces a blocked by your AV message. See attached screenshot.
![image](https://user-images.githubusercontent.com/43847240/98132592-8341b480-1eb4-11eb-844d-14b92688ba9f.png)

**Comment by eXPeri3nc3** [comment]
Hi RhythmStick!

I tried, and yes it's being blocked - similar to your screenshot. Would that mean that I need to bypass that first ('AMSIScanBuffer') before I can see other triggers that the ps1 may still have?

Or did I misunderstand the error that I need to disable realtime protection before using AMSITrigger?

![image](https://user-images.githubusercontent.com/23732360/98136377-d4c16200-1efb-11eb-925c-2058d89d6db7.png)

Also just tried disabling WinDef and I still get the error (I ran it on vanilla Invoke-Mimikatz in a whitelisted directory)
![image](https://user-images.githubusercontent.com/23732360/98137190-aee88d00-1efc-11eb-92c8-4bd6bffa1e58.png)

**Comment by RythmStick** [comment]
No you didnt misunderstand. The fact that you generated the AV alert when you passed it "AMSIScanbuffer" proves that real time protection is on - which it needs to be. What it doesnt help with is why AMSITrigger thinks that real time protection is switched off, because its effectively doing exactly that. Do you have any exceptions in place maybe for that d:\ drive ?

**Comment by RythmStick** [comment]
so for instance, if you run powershell as an admin, 
![image](https://user-images.githubusercontent.com/43847240/98141075-192e0d00-1ebe-11eb-9921-37c68a99bf11.png)

**Comment by eXPeri3nc3** [comment]
Yes I did add Exclusion path, else the Invoke-Mimikatz would automatically be removed by Defender when I run AMSITrigger

![image](https://user-images.githubusercontent.com/23732360/98142089-561bf300-1f02-11eb-866d-1c0fdd62eb0b.png)

**Comment by eXPeri3nc3** [comment]
This is how it looks like: 
![image](https://user-images.githubusercontent.com/23732360/98142441-c32f8880-1f02-11eb-91d6-a8855533a935.png)

**Comment by RythmStick** [comment]
Sure - my question was more about is there an exclusion  for the folder where the AMSITrigger assembly is, rather than the target.

**Comment by RythmStick** [comment]
could you try copying invoke-mimikatz.ps1 to another (non-excluded) folder with a different name, eg. invoke-mimi.ps1 and then try AMSITrigger on that file.

**Comment by eXPeri3nc3** [comment]
> could you try copying invoke-mimikatz.ps1 to another (non-excluded) folder with a different name, eg. invoke-mimi.ps1 and then try AMSITrigger on that file.

Yes sure, as follows:
![image](https://user-images.githubusercontent.com/23732360/98144232-1d314d80-1f05-11eb-8b5d-a25e434d7ce7.png)

No exclusions in my home folder, renamed, showed something slightly diff this round

Similar error with PS as the terminal:
![image](https://user-images.githubusercontent.com/23732360/98144707-79946d00-1f05-11eb-9e8d-c761cf0f11cd.png)

**Comment by RythmStick** [comment]
![image](https://user-images.githubusercontent.com/43847240/98144316-2b11af00-1ec2-11eb-84a3-83592bbbeb2e.png)

**Comment by RythmStick** [comment]
which version of AMSITrigger you running - just so we have like-for-like

**Comment by eXPeri3nc3** [comment]
> which version of AMSITrigger you running - just so we have like-for-like

I was running the build v2 x86 for prior examples.

I just figured out what triggers the Check realtime protection message.
If I chose in Defender to allow the files on the PC that error message will occur. Else the file will be removed and it will show back the same Unhandled Exception error message

![image](https://user-images.githubusercontent.com/23732360/98146164-53bb9800-1f06-11eb-9322-71a398cffc9c.png)
^  This was run with your latest codebase

**Comment by RythmStick** [comment]
yeah - I understand that 2nd case as defender is quite-rightly removing the malicious file before AMSITrigger tries to open it. In the 2nd case (no exclusion in place)  can you run AMSITrigger without any parameters

**Comment by eXPeri3nc3** [comment]
> yeah - I understand that 2nd case as defender is quite-rightly removing the malicious file before AMSITrigger tries to open it. In the 2nd case (no exclusion in place) can you run AMSITrigger without any parameters

![image](https://user-images.githubusercontent.com/23732360/98147253-3cc97580-1f07-11eb-957f-8e92db766aab.png)

Yes it runs and shows the above

**Comment by RythmStick** [comment]
yeah - I understand that 2nd case as defender is quite-rightly removing the malicious file before AMSITrigger tries to open it.

**Comment by RythmStick** [comment]
Could you look at the properties of this file:
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
in explorer and tell me what product version it is (details tab)

**Comment by RythmStick** [comment]
It might be worth matching up your version with this [line](https://github.com/RythmStick/AMSITrigger/blob/3cd36eed67850dda9824505ccd927d38723618fa/AMSITrigger/Program.cs#L169). Just change the `powershell.exe_10.0.18362.1` to match yours, recompile, then try again.

**Comment by eXPeri3nc3** [comment]
> Could you look at the properties of this file:
> C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
> in explorer and tell me what product version it is (details tab)

Please see below:
![image](https://user-images.githubusercontent.com/23732360/98150997-764fb000-1f0a-11eb-8f09-9500031d961d.png)

**Comment by RythmStick** [comment]
Let me know how that goes.

**Comment by RythmStick** [comment]
so change to powershell.exe_10.0.19041.546

**Comment by eXPeri3nc3** [comment]
> so change to powershell.exe_10.0.19041.546

Got it, will revert when I managed to compile. Didn't realise the VS I was using was Professional and the trial period expired - getting the Community version installer now

**Comment by eXPeri3nc3** [comment]
> so change to powershell.exe_10.0.19041.546

![image](https://user-images.githubusercontent.com/23732360/98152974-77cea780-1f0d-11eb-8148-1eba5155e136.png)

No luck. I removed the allowed threats just to be sure and the same error still occurs

**Comment by S3cur3Th1sSh1t** [comment]
Just put the `.ps1` file and the `AmsiTrigger.exe` in an AV-excluded folder. ;-)

**Comment by RythmStick** [comment]
Pretty sure that's been tried S3curTh1sSh1t but happy to try anything at this point..

**Comment by eXPeri3nc3** [comment]
> Just put the `.ps1` file and the `AmsiTrigger.exe` in an AV-excluded folder. ;-)

Holyshit that actually worked!

![image](https://user-images.githubusercontent.com/23732360/98155551-64bdd680-1f11-11eb-8639-fcdefc9c0d90.png)

**Comment by eXPeri3nc3** [comment]
So I guess the fix is to whitelist the folder that AMSITrigger is running from 

Thank you RythmStick (for spending time to diagnose) & S3cur3Th1sSh1t for the suggestion

**Comment by S3cur3Th1sSh1t** [comment]
Instead you could also "obfuscate" Amsitrigger by changing the namespace and class names before compilation but the exclusion is the easiest way so far. :rocket:

**Comment by RythmStick** [comment]
Just glad it's working 😊 thanks S3cur3Th1sSh1t

**Comment by unch4rt3d** [comment]
Even if this issue is considered closed, I'd like to add something for Win 10/11 22H2 builds and the according Defender versions:
As Windows Defender now ignores directory exclusions for **really** bad binaries, the tool can hardly be used. If you exclude the directory for AMSITrigger, the binary's process will be blocked by Defender nonetheless. If you exclude the process directly, the tool will output that real time protection is not enabled. No easy way around Windows Defender in 2023. I guess I'd need to try an older version of Windows/Defender or obfuscating the whole thing itself...
Nonetheless I'd like to thank you @RythmStick for the effort and the nice idea!

**Comment by Ab4y98** [comment]
> Even if this issue is considered closed, I'd like to add something for Win 10/11 22H2 builds and the according Defender versions: As Windows Defender now ignores directory exclusions for **really** bad binaries, the tool can hardly be used. If you exclude the directory for AMSITrigger, the binary's process will be blocked by Defender nonetheless. If you exclude the process directly, the tool will output that real time protection is not enabled. No easy way around Windows Defender in 2023. I guess I'd need to try an older version of Windows/Defender or obfuscating the whole thing itself... Nonetheless I'd like to thank you [@RythmStick](https://github.com/RythmStick) for the effort and the nice idea!

Any idea which version of Windows this tool can still work with?

**Comment by NathObeaN** [comment]
I don't believe this works anymore. I tried this back in November 2024 and it worked fine. However, trying again on the same machine with the same snapshot, as soon as I allow internet connectivity, it appears to download an update which prevents AMSITrigger.exe from talking to AMSI, so it always responds with "Check Real Time protection is enabled". This is despite Defender being fully enabled and not blocking the application/process. I even recompiled the program with custom properties and it's the same behaviour. MS must have locked down the API that AMSITrigger relies on to report back.

**Comment by axwl03** [comment]
I think it's still working. The logic for [protectionEnabled](https://github.com/RythmStick/AMSITrigger/blob/master/AMSITrigger/Triggers.cs#L270) required some modification. Currently, the workaround I’m using is to always return true in this function, and it works as intended.

**Comment by RythmStick** [comment]
I need to take a look, but I suspect that AV no longer triggers on the string AMSIScanBuffer. You can probably change line 273 in triggers.cs to something like ...GetBytes("invoke-mimikatz") which should get flagged by AV, then recompile.

**Comment by axwl03** [comment]
> I suspect that AV no longer triggers on the string AMSIScanBuffer

Agreed. I've tested it and `AMSIScanBuffer` didn't trigger AV.
`Invoke-Mimikatz` should be a better trigger instead of the workaround.
Thanks for the great tool again @RythmStick !
