### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by eescanilla** [RythmStick/AMSITrigger#6]
When executing it may give a communication error The request was aborted: Could not create SSL/TLS secure channel, the following could be added before the instance to the url parameter:

ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

GJ.

regards.

**Comment by RythmStick** [comment]
Should be addressed now - just merged PR from S3cur3Th1sSh1t
